close all,
clear variables,
clc
addpath('./plot_google_map/');


%% Import CSV files of Matrice, generated by Airdata website
file_list = dir(fullfile("C:\Users\ioste\OneDrive - Politecnico di Milano\PhD\projects\UAV SAR\dataset\20230616\drone track\*.csv"));

for  ii = 1: numel(file_list)

    fname = strcat(file_list(ii).folder, "\",file_list(ii).name);
    gps_raw = readtable(fname);
    %%
    gps_time = datetime(gps_raw.datetime_utc_(1), ...
        'InputFormat','yyyy-MM-dd''T''HH:mm:ss.SSS''Z','Format','yyyy-MM-dd HH:mm:ss.SSS');% + hours(2);
    
    gps_time = gps_time + milliseconds(gps_raw.time_millisecond_) - milliseconds(gps_raw.time_millisecond_(1));

    gps_matrice = table();
    gps_matrice.UTC = gps_time;
    gps_matrice.lat = gps_raw.latitude;
    gps_matrice.lon = gps_raw.longitude;
    gps_matrice.alt = gps_raw.altitude_above_seaLevel_meters_; %gps_raw.height_above_takeoff_meters_;
    gps_matrice.speed = gps_raw.speed_m_s_;
    gps_matrice.yaw = gps_raw.compass_heading_degrees_;
    gps_matrice.pitch = gps_raw.pitch_degrees_;
    gps_matrice.roll = gps_raw.roll_degrees_;

    %% to ENU

    if ~ exist("lla0","var")
        lla0 = [gps_matrice.lat(1) gps_matrice.lon(1) gps_matrice.alt(1)]; % lat, lon, alt
    end
    ENU = lla2enu([gps_matrice.lat, gps_matrice.lon, gps_matrice.alt],lla0,'flat');
    gps_matrice.X = ENU(:,1);
    gps_matrice.Y = ENU(:,2);
    gps_matrice.Z = ENU(:,3);

    figure(1), plot(gps_matrice.lon,gps_matrice.lat,LineWidth=1.5)
    xlabel("Longitude"),ylabel("Latitude"), axis("xy"),hold on
    %% Get antenna positions
    UAVtoTx = [9, 88, 31] .*1e-2;
    UAVtoRx = [9, -88, 31] .*1e-2;
    POSE = calcAntennaPositions(gps_matrice,UAVtoTx,UAVtoRx);
    %%
    save(strcat("track_matrice_",num2str(ii)),"POSE")
    save("lla0","lla0")
end
return
%% targets
% Corner 45.8316863 9.3605287
% Furgone 45.8317537 9.3606571
% Golf 45.8317043 9.3602124
% Peugeot 45.8315148 9.3602073

targets(1).lat = 45.8316863; targets(1).lon = 9.3605287;
targets(2).lat = 45.8317537; targets(2).lon = 9.3606571;
targets(3).lat = 45.8317043; targets(3).lon = 9.3602124;
targets(4).lat = 45.8315148; targets(4).lon = 9.3602073;


for ii = 1:numel(targets)
    ENU  = lla2enu([targets(ii).lat, targets(ii).lon, lla0(3)],lla0,'flat');
    targets(ii).X = ENU(1);targets(ii).Y = ENU(2); targets(ii).Z =  ENU(3);
    figure(1),plot(targets(ii).lon,targets(ii).lat,'^r',LineWidth=1),hold on
end
save("targets","targets")

%% Add Google maps satellite view
plot_google_map('MapType','satellite');
